plugins:
  cryptocurrencies_enabled:
    default: false
    client: true
  cryptocurrencies_new_topic_owner:
    type: username
    default: "system"
    client: true
  cryptocurrencies_new_topic_category:
    type: category_list
    default: ''