plugins:
  cryptocurrencies_enabled:
    default: false
    client: true
  cryptocurrencies_new_topic_owner:
    type: username
    default: "system"
    client: true
  cryptocurrencies_new_topic_category:
    type: category_list
    default: ''
basic:
  top_menu:
    client: true
    refresh: true
    type: list
    default: "latest|new|unread|top|categories"
    regex: "latest"
    regex_error: "site_settings.errors.must_include_latest"
    choices:
     - latest
     - new
     - unread
     - top
     - categories
     - read
     - posted
     - bookmarks
     - home